version: '3'

services:
  # Node.js application service
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: benefit-consultation-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis_cache
    environment:
      - REDIS_HOST=redis_cache
      - REDIS_PORT=6379

  # Redis cache service
  redis_cache:
    image: "redis:alpine"
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
